// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig, env } from "prisma/config";
import { assertDatabaseTarget, formatDatabaseTarget } from "./lib/db/target-guard";

const target = assertDatabaseTarget({ purpose: "prisma" });
console.log(formatDatabaseTarget(target));

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
